import Sidebar from '@/components/Sidebar'
import './globals.css'


export const metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body className='flex'>

        <Sidebar/>
        <main className='ml-20 w-full'>
        {children}
        </main>
        
        
        
        </body>
    </html>
  )
}
